apps/cpa/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from apps.cpa.views import *


urlpatterns = patterns('',
    url(r'^$', CostSettingView.as_view(), name='cost_setting'),
    url(r'^report-click/$', ReportClickView.as_view(), name='report_click'),
    url(r'^report-click-xml/(?P<report_key>[._\w]+)/$', ReportClickXMLView.as_view(), name='report_xml'),

    url(r'^get-category-cost/$', JsonCategoryCostView.as_view(), name='url_get_category_cost'),
    url(r'^get-category-cost/(?P<section_id>\d+)$', JsonCategoryCostView.as_view(), name='get_category_cost'),

    url(r'^get-category-by-site/(?P<site_id>\d+)/$', JsonUserCategoryBySiteView.as_view(), name='get_category_by_site'),
    url(r'^update-cost/$', EditCostView.as_view(), name='update_cost'),


    url(r'^transition/(?P<product_id>\d+)/$', TransitionView.as_view(), name='transition'),
)

source/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page

from apps.website.views import SearchView
from apps.account.views import (
    SignupOnlineMarketFormView,
    SignupOfflineMarketFormView
)

CACHE_TIMEOUT_SEARCH = 20*60 #20 minutes

admin.autodiscover()

urlpatterns = patterns('',
  
                       url(r'^admin/mailto/$', 'apps.dashboard.admin.mailto', name='mailto'),
                       url(r'^$', 'apps.website.views.index', name='index'),

                       #url(r'^search/$', 'apps.website.views.search',  name='search'),
                       #url(r'^search/$', cache_page(CACHE_TIMEOUT_SEARCH)(SearchView.as_view()), name='search'),
                       url(r'^search/$', SearchView.as_view(),  name='search'),
                       url(r'^asearch/$', 'apps.website.views.search_autocomplete', name='search_autocomplete'),

                       url(r'^website/$', 'apps.website.views.website', name='website'),

#                       url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),
#                       url(r'^dealers/$', TemplateView.as_view(template_name="dealers.html"), name='dealers'),
#                       url(r'^jobs/$', TemplateView.as_view(template_name="jobs.html"), name='jobs'),
#                       url(r'^price/$', TemplateView.as_view(template_name="price.html"), name='price'),

                       url(r'^connect_shop/$', 'apps.feedback.views.connect_shop', name='connect_shop'),
                       url(r'^connect_shop/send/$', 'apps.feedback.views.connect_shop_send', name='connect_shop_send'),

#                       url(r'^advertisement/$', TemplateView.as_view(template_name="advertisement.html"), name='advertisement'),
#                       url(r'^protect/$', TemplateView.as_view(template_name="protect.html"), name='protect'),

                       url(r'^support/$', 'apps.feedback.views.support', name='support'),

                       url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}, name='logout'),
                       # TODO remove
                       url(r'^signup/$', 'apps.account.views.signup', name='signup'),
                       url(r'^signup2/$', 'apps.account.views.signup2', name='signup2'),
                       url(r'^signup3/$', 'apps.account.views.signup3', name='signup3'),

                       url(r'^signup_online/$', SignupOnlineMarketFormView.as_view(), name='signup_online'),
                       url(r'^signup_offline/$', SignupOfflineMarketFormView.as_view(), name='signup_offline'),

                       url(r'^admin/', include(admin.site.urls)),
                       # url(r'^force_reindex/$', 'apps.website.views.force_update_index', name='force_index_update'),

                       url(r'^banner/', include('apps.banner.urls')),
                       url(r'^dashboard/', include('apps.dashboard.urls')),

                       url(r'^a/', include('apps.account.urls')),
                       url(r'^w/', include('apps.website.urls')),
                       url(r'^c/', include('apps.catalog.urls')),
                       url(r'^p/', include('apps.pages.urls')),
                       url(r'^n/', include('apps.news.urls')),
                       url(r'^v/', include('apps.version.urls')),
                       url(r'^t/', include('apps.ticket.urls')),
                       url(r'^d/', include('apps.distribution.urls')),
                       
                       #url(r'^api/v1/', include('apps.api_rest.urls')),

                       url(r'^section/', include('apps.section.urls')),
                       url(r'^bid/', include('apps.cpa.urls')),
                       url(r'^coupon/', include('apps.coupon.urls')),
                       url(r'^page/', include('django.contrib.flatpages.urls')),
                )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cpa/models.py
# -*- coding: utf-8 -*-

#Django imports
from django.db import models
from django.contrib.auth.models import User

#findinshop
from apps.section.utils import EnumChoices
from apps.catalog.models import Item, Category
from apps.website.models import Website
from apps.section.models import Section
from apps.cpa.validators import min_cost_rate


BASE_COST = 0


class CostSetting(models.Model):
    user = models.ForeignKey(User)
    section = models.ForeignKey(Section)
    count_item = models.IntegerField(u'Количество товаров в разделе', default=0)
    base_cost = models.FloatField(u'Базовая стоимость клика', default=BASE_COST)
    current_rate = models.FloatField(u'Текущая ставка', default=0, validators=[min_cost_rate])
    total_cost = models.FloatField(u'Общая стоимость клика', default=0)
    date_change = models.DateTimeField(auto_now=True)
    changed = models.BooleanField(u'Менялась ставка?', default=False)

    def __unicode__(self):
        return u'Настройки стоимости клика для %s' % self.user


class Report(models.Model):
    user = models.ForeignKey(User)
    section = models.ForeignKey(Section, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    product_name = models.CharField(u'Товар', max_length=255)
    cost = models.FloatField(u'Стоимость клика')
    ip = models.CharField(u'IP адрес', max_length=20, null=True, blank=True)
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = u'Отчет о кликах'
        verbose_name_plural = u'Отчеты о кликах'


class OwnAndUserCategory(models.Model):
    site = models.ForeignKey(Website, verbose_name=u'Web сайт')
    our_section = models.ForeignKey(Section, verbose_name=u'Наш раздел')
    categories = models.ManyToManyField(
        Category, verbose_name=u'Пользовательские категории')

    def __unicode__(self):
        return u'Web сайт: %s, Категория: %s' % (self.site, self.our_section)

    class Meta:
        ordering = ('site',)
        verbose_name = u'Связь собственных и юзерских категорий'
        verbose_name_plural = u'Связи собственных и юзерских категорий'


class RefreshCostTask(models.Model):
    STATUS = EnumChoices((
        (0, u'Принят', 'NEW'),
        (1, u'Обрабатывается', 'PROCESSING'),
        (2, u'Выполнен', 'DONE'),
        (3, u'Ошибка выполнения', 'ERROR'),
    ))

    setting = models.ForeignKey(CostSetting)
    item_count = models.IntegerField(
        u'Количество переоцененных товаров', default=0)
    # Info
    status = models.IntegerField(verbose_name=u'Статус задания', choices=STATUS, default=0)
    start = models.DateTimeField(verbose_name=u'Начало выполнения', blank=True, null=True)
    complete = models.DateTimeField(verbose_name=u'Конец выполнения', blank=True, null=True)
    error = models.TextField(verbose_name=u'Код ошибки', blank=True, null=True)

    def __unicode__(self):
        return u'Задача на переоценку для %s в категории - %s' % (self.setting.user, self.setting.section)

    class Meta:
        verbose_name = u'Задание переоценки раздела'
        verbose_name_plural = u'Задания переоценки раздела'

apps/cpa/forms.py
# -*- coding: utf-8 -*-

#Python imports
from datetime import timedelta

#Django imports
from django import forms
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.core.cache import cache

#Findinshop
from apps.cpa.models import CostSetting, OwnAndUserCategory
from apps.cpa.validators import MIN_COST_RATE
from apps.cpa.utils import float_to_python
from apps.section.models import Section
from apps.catalog.models import Category
from apps.website.models import Website


class CategoryCostForm(forms.ModelForm):

    class Meta:
        model = CostSetting
        fields = ('section', 'current_rate')

    def __init__(self, *args, **kwargs):
        super(CategoryCostForm, self).__init__(*args, **kwargs)
        self.fields['section'].queryset = Section.parents.all()
        self.fields['current_rate'].help_text = 'Минимальная стоимость %s грн.' % MIN_COST_RATE
        self.fields['current_rate'].to_python = float_to_python

    def clean(self):
        cleaned_data = super(CategoryCostForm, self).clean()
        section = cleaned_data.get('section')
        if section and self.user:
            #setting = get_object_or_404(CostSetting, user=self.user, section=section)
            setting, created = CostSetting.objects.get_or_create(user=self.user, section=section)

            if setting.current_rate == cleaned_data.get('current_rate'):
                raise forms.ValidationError(u'Такая ставка уже установлена.')

            if setting.changed is True:
                time_tree_hour_ago = timezone.now() - timedelta(hours=3)

                if time_tree_hour_ago < setting.date_change:
                    raise forms.ValidationError(u'Повторное изменение ставки на эту категорию возможно через 3 часа')

        return cleaned_data


class OwnAndUserCategoryForm(forms.ModelForm):

    class Meta:
        model = OwnAndUserCategory
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(OwnAndUserCategoryForm, self).__init__(*args, **kwargs)

        #if not cache.get('key_queryset_section_children_admin', False):
        #    queryset_section = Section.children.all().order_by('parent__name')
        #    cache.set('key_queryset_section_children_admin', queryset_section, 2*3600)#2 hours
        #else:
        #    queryset_section = cache.get('key_queryset_section_children_admin')

        #self.fields['our_section'].queryset = queryset_section


        self.fields['our_section'].queryset = Section.parents.all()

        if self.instance.pk:
            self.fields['categories'].queryset = Category.objects.filter(catalog=self.instance.site.catalog)
        else:
            self.fields['categories'].choices = Category.objects.none()

        self.fields['site'].queryset = Website.objects.order_by('subdomain')


class ReportClickForm(forms.Form):

    date_from = forms.DateField(
                    label=u'Начиная с даты',
                    #input_formats='%d.%m.%Y'
            )
    date_to = forms.DateField(
                    label=u'Заканчивая датой',
                    #input_formats='%d.%m.%Y'
            ) 

apps/cpa/templates/cpa/cost_setting.html
{% extends "base.catalog.html" %}

{% block manage_bar %}
    {% include 'manage.tabs.html' with cost_setting=1 %}
{% endblock %}

{% block title %}Настройки стоимости клика{% endblock %}

{% block third_party_css %}
    <style>.hidden{display: none;}</style>
{% endblock third_party_css %}


{% block js %}

        function clean_data(value){
            return value.toString().replace('.', ',');
        }

        $(function(){
            $('.load-children').click(function(){
                var section_id = $(this).data('id'),
                    url_json_category = '{% url "url_get_category_cost" %}';

                if ($(this).data('status') == 'empty'){
                    
                    $.getJSON(url_json_category+section_id, function(res){
                        var answer = '';
                        for(var i in res){
                            answer += '<tr><td>&nbsp;&nbsp;&nbsp;- '+res[i].name+'</td><td>'+res[i].base_cost+'</td><td>'+res[i].current_rate+'</td><td>'+res[i].total_cost+'</td><td><div class="btn-group" style=""><a class="btn btn-mini category-cost" href="#" data-rate="'+res[i].current_rate+'" data-id="'+res[i].id+'" data-name="'+res[i].name+'"><i class="icon-edit"></i></a></div></td></tr>'
                        }
                        $('#section-'+section_id).after(answer);
                        $('#id-section-'+section_id).data('status', 'loaded');
                    });

                }

                return false;

            });

            $('.category-cost').live('click', function(){
                $('#category-name b').html($(this).data('name'));
                $('#id_section').val($(this).data('id'));
                $('#id_current_rate').val($(this).data('rate'));

                //return false;
            });

            $('.change_rate').click(function(){
                $(this).addClass('selected');
            });

            $('.change_rate.selected').live('mouseout', function(){

                var self = $(this);

                $(this).removeClass('selected')
                       .blur();

                if ( clean_data($(this).val()) !== clean_data($(this).data('value')) ){
                    var url = '/bid/update-cost/';

                    //remove messages
                    $('.alert.alert-info.alert-block').remove();
                    $(this).after('<img width="28" height="28" src="/static/img/ajax-loader.gif" />');
                    
                    $.get(url, {section: $(this).data('id'), current_rate: clean_data($(this).val())}, function(data){
                        if (data['status'] == 'ok'){
                            self.data('value', clean_data(self.val()));
                            self.val(clean_data(self.val()));
                            $('#total'+self.data('id')).html(clean_data(data['total']));
                            $('.nav.nav-pills').before('<div class="alert alert-info alert-block" style="text-align: justify;"><button type="button" class="close" data-dismiss="alert">×</button><p>'+data['message']+'</p></div>');
                        } else {
                            self.val(clean_data(self.data('value')));
                            $('.nav.nav-pills').before('<div class="alert alert-info alert-block" style="text-align: justify;"><button type="button" class="close" data-dismiss="alert">×</button><p>'+data['message'][0]+'</p></div>');
                        }
                    });

                    $(this).next().remove();
                }
            });

                //var new_val = $(this).val();
                //if ( !new_val ){
                    //new_value = 1.2;
                //}

        });

{% endblock %}



{% block column  %}

    {% if messages %}
        <div class="alert alert-info alert-block" style="text-align: justify;">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <ul class="nav nav-pills">
        <li class="active"><a href="{% url "cost_setting" %}">Настройка стоимости клика</a></li>
        <li><a href="{% url "report_click" %}">Отчет о кликах</a></li>
    </ul>

    <!--form action="" method="post">{% csrf_token %}
        <p id="category-name">Редактирование ставки для <b>Выберите раздел для редактирования...</b></p>
        <p>
            {{ form.non_field_errors }}
            {{ form.current_rate.errors }}
        </p>
        <p>
            {{ form.current_rate.label }}:<br />
            {{ form.current_rate }}
            &nbsp;<span class="small">{{ form.current_rate.help_text }}</span>
        </p>
        <p class="hidden">{{ form.section }}</p>
        <input type="submit" value="Изменить ставку" />
    </form-->

    <table width="100%">
        <tr>
            <td><b>Название категории</b></td>
            <td><b>Базовая стоимость(грн)</b></td>
            <td><b>Текущая ставка(грн)</b></td>
            <td><b>Общая стоимость клика(грн)</b></td>
        </tr>
        {% if sections %}
            {% for section in sections %}
                <tr id="section-{{ section.pk }}">
                    <td>{{ section.name }}</td>
                    <td>{% if not section.base_cost %}0{% else %}{{ section.base_cost }}{% endif %}</td>
                    <td><input type="text" class="change_rate" data-id="{{ section.id }}" data-value="{% if not section.current_rate %}0{% else %}{{ section.current_rate }}{% endif %}" value="{% if not section.current_rate %}0{% else %}{{ section.current_rate }}{% endif %}" /></td>
                    <td id="total{{ section.id }}">{% if not section.total_cost %}0{% else %}{{ section.total_cost }}{% endif %}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock %}

apps/cpa/templates/cpa/report_click.html
{% extends "base.catalog.html" %}

{% block manage_bar %}
    {% include 'manage.tabs.html' with cost_setting=1 %}
{% endblock %}

{% block title %}Отчет о кликах{% endblock %}

{% block third_party_css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <style>
        form p{float: left; margin-right: 10px;}
        div.clear{height: 1px; clear: both;}
    </style>
{% endblock third_party_css %}


{% block bottom_js %}
<script type="text/javascript" src="{{ STATIC_URL }}js/datepicker/jquery.ui.datepicker.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/datepicker/jquery.ui.datepicker-ru.js"></script>
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript">
    $(function(){
          $.datepicker.setDefaults({
            dateFormat: 'mm/dd/yy',
            prevText: '',
            nextText: '',
          });

        $('#id_date_from').datepicker();
        $('#id_date_to').datepicker();
    });
</script>
{% endblock %}


{% block column  %}

    {% if messages %}
        <div class="alert alert-info alert-block" style="text-align: justify;">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    <ul class="nav nav-pills">
        <li><a href="{% url 'cost_setting' %}">Настройка стоимости клика</a></li>
        <li class="active"><a href="{% url 'report_click' %}">Отчет о кликах</a></li>
    </ul>

    <form action="" method="get">
        {{ form.as_p }}
        <p><label>&nbsp;</label><input type="submit" value="Вывести отчет" /></p>
    </form>

    <div class="clear"></div>

    {% if reports %}
        <table class="table">
            <thead>
                <tr>
                    <td colspan="4">Отчет за период {{ from }} - {{ to }}</td>
                    <td colspan="2"><a class="btn-link" href="{% url 'report_xml' report_key %}"><i class="icon-download"></i>Скачать XLS</a></td>
                </tr>
                <tr>
                    <td><b>Раздел</b></td>
                    <td><b>Собственная категория</b></td>
                    <td><b>Продукт</b></td>
                    <td><b>Стоимость клика(грн.)</b></td>
                    <td><b>IP клика</b></td>
                    <td><b>Дата\Время</b></td>
                </tr>
            </thead>
                {% for report in reports %}
                    <tr>
                        <td>{{ report.section.name }}</td>
                        <td>{{ report.category }}</td>
                        <td>{{ report.product_name }}</td>
                        <td>{{ report.cost }}</td>
                        <td>{% if report.ip %}{{ report.ip }}{% else %}-{% endif %}</td>
                        <td>{{ report.date|date:"d.m.Y H:i" }}</td>
                    </tr>
                {% endfor %}
        </table>
    {% elif from and to %}
        <p>Нет отчета на данный период.</p>
    {% else %}
        <p>Укажите временной отрезок для по которому хотите получить отчет.</p>
    {% endif %}


{% endblock %}